# Generated by Django 3.1.1 on 2020-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Size', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
                ('Stocks', models.CharField(max_length=3)),
                ('Price', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
