# Generated by Django 3.1.1 on 2020-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Stocks',
            field=models.CharField(max_length=5),
        ),
    ]
