# Generated by Django 3.1.1 on 2020-09-24 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200920_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datereg',
            field=models.DateField(default=datetime.datetime(2020, 9, 24, 20, 54, 34, 968150)),
        ),
    ]
